services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      cd web-portfolio
      npm install
      npm run build
    staticPublishPath: ./web-portfolio/dist
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    autoDeploy: true
